### PR TITLE
neighbours: peer-group members, next-hop-self, description

### PR DESCRIPTION
**Pull request by robbat2**
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

### CODE REVIEW

**Comment by robbat2** [comment]
Pending Travis check for new test cases.

**Comment by robbat2** [comment]
@floored1585 review/merge/release please?

**Comment by robbat2** [comment]
Improvements made to the test suite to ensure order of items is correct, and helped find bugs in my other new code with it already :-). Passes cleanly now.

**Review by nertwork — COMMENTED** [review]
Looks good to me but floored1585 should approve

**Pull request merged**
